version: '2.2'
services:
  go-agent1:
    image: gocd-agent-tumbleweed-release-tools
    build:
       context: docker-gocd-agent-tumbleweed-release-tools
    environment:
      AGENT_AUTO_REGISTER_KEY: '75a7b26d-fc5e-4ccf-88c9-cbf61afc7ebb'
      GO_SERVER_URL: https://botmaster.suse.de:8154/go
      AGENT_AUTO_REGISTER_RESOURCES: staging-bot
    volumes:
      - /srv/go-config:/home/go/config
    scale: 15
  
  go-agent2:
    image: gocd-agent-tumbleweed-release-tools
    environment:
      AGENT_AUTO_REGISTER_KEY: '75a7b26d-fc5e-4ccf-88c9-cbf61afc7ebb'
      GO_SERVER_URL: https://botmaster.suse.de:8154/go
      AGENT_AUTO_REGISTER_RESOURCES: repo-checker
    volumes:
      - /srv/go-repository-cache:/home/go/.cache/openSUSE-release-tools/repository-meta/
      - /srv/go-config:/home/go/config
    scale: 6
  
  go-agent3:
    image: gocd-agent-tumbleweed-release-tools
    environment:
      AGENT_AUTO_REGISTER_KEY: '75a7b26d-fc5e-4ccf-88c9-cbf61afc7ebb'
      GO_SERVER_URL: https://botmaster.suse.de:8154/go
      AGENT_AUTO_REGISTER_RESOURCES: leaper
    volumes:
      - /srv/go-config:/home/go/config
      - /etc/openSUSE-release-tools/manager_42/:/etc/openSUSE-release-tools/manager_42/

