format_version: 3
pipelines:
  openSUSE.openQA:
    group: Monitors
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 */5 * ? * *
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    materials:
      git:
        git: https://github.com/coolo/osc-plugin-factory.git
        branch: add_repoid_monitor
    stages:
    - Run:
        approval:
          type: manual
        jobs:
          Run:
            timeout: 0
            resources:
            - staging-bot
            tasks:
            - script: |-
                ./rabbit-openqa.py -A https://api.opensuse.org
  SUSE.openQA:
    group: Monitors
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 */5 * ? * *
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    materials:
      git:
        git: https://github.com/coolo/osc-plugin-factory.git
        branch: add_repoid_monitor
    stages:
    - Run:
        approval:
          type: manual
        jobs:
          Run:
            timeout: 0
            resources:
            - staging-bot
            tasks:
            # endless loop
            - script: |-
                ./rabbit-openqa.py -A https://api.suse.de
  SUSE.Repo.Monitor:
    group: Monitors
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 */5 * ? * *
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    materials:
      git:
        git: https://github.com/coolo/osc-plugin-factory.git
        branch: add_repoid_monitor
    stages:
    - Run:
        approval:
          type: manual
        jobs:
          Run:
            timeout: 0
            resources:
            - staging-bot
            tasks:
            # endless loop
            - script: |-
                git config --global user.email "coolo@suse.de"
                git config --global user.name "GoCD Repo Monitor"
                git clone https://github.com/openSUSE/osc.git --depth 1 -b python3
                git clone git://botmaster.suse.de/suse-repos.git
                cd suse-repos
                export PYTHONPATH=../osc:/usr/share/openSUSE-release-tools
                python3 ../rabbit-repoid.py -A https://api.suse.de SUSE:SLE-15-SP1:GA
  openSUSE.Repo.Monitor:
    group: Monitors
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 */5 * ? * *
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    materials:
      git:
        git: https://github.com/coolo/osc-plugin-factory.git
        branch: add_repoid_monitor
    stages:
    - Run:
        approval:
          type: manual
        jobs:
          Run:
            timeout: 0
            resources:
            - staging-bot
            tasks:
            # endless loop
            - script: |-
                git config --global user.email "coolo@suse.de"
                git config --global user.name "GoCD Repo Monitor"
                git clone https://github.com/openSUSE/osc.git --depth 1 -b python3
                git clone git://botmaster.suse.de/opensuse-repos.git
                cd opensuse-repos
                export PYTHONPATH=../osc:/usr/share/openSUSE-release-tools
                python3 ../rabbit-repoid.py -A https://api.opensuse.org openSUSE:Factory openSUSE:Leap
