format_version: 3
pipelines:

  Pkglistgen.Factory_Staging.A:
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    timer:
      spec: 0 */30 * ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/coolo/citest.git
    stages:
    - pkglistgen:
        approval: manual
        jobs:
          openSUSE_Factory:
            resources:
            - repo-checker
            tasks:
            - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve --staging openSUSE:Factory:Staging:A --force

  Pkglistgen.Factory_Staging.B:
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    timer:
      spec: 0 */30 * ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/coolo/citest.git
    stages:
    - pkglistgen:
        approval: manual
        jobs:
          openSUSE_Factory:
            resources:
            - repo-checker
            tasks:
            - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve --staging openSUSE:Factory:Staging:B --force

  Pkglistgen.Factory_Staging.C:
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    timer:
      spec: 0 */30 * ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/coolo/citest.git
    stages:
    - pkglistgen:
        approval: manual
        jobs:
          openSUSE_Factory:
            resources:
            - repo-checker
            tasks:
            - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve --staging openSUSE:Factory:Staging:C --force

  Pkglistgen.Factory_Staging.D:
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    timer:
      spec: 0 */30 * ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/coolo/citest.git
    stages:
    - pkglistgen:
        approval: manual
        jobs:
          openSUSE_Factory:
            resources:
            - repo-checker
            tasks:
            - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve --staging openSUSE:Factory:Staging:D --force

  Pkglistgen.Factory_Staging.E:
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    timer:
      spec: 0 */30 * ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/coolo/citest.git
    stages:
    - pkglistgen:
        approval: manual
        jobs:
          openSUSE_Factory:
            resources:
            - repo-checker
            tasks:
            - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve --staging openSUSE:Factory:Staging:E --force

  Pkglistgen.Factory_Staging.F:
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    timer:
      spec: 0 */30 * ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/coolo/citest.git
    stages:
    - pkglistgen:
        approval: manual
        jobs:
          openSUSE_Factory:
            resources:
            - repo-checker
            tasks:
            - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve --staging openSUSE:Factory:Staging:F --force

  Pkglistgen.Factory_Staging.G:
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    timer:
      spec: 0 */30 * ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/coolo/citest.git
    stages:
    - pkglistgen:
        approval: manual
        jobs:
          openSUSE_Factory:
            resources:
            - repo-checker
            tasks:
            - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve --staging openSUSE:Factory:Staging:G --force

  Pkglistgen.Factory_Staging.H:
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    timer:
      spec: 0 */30 * ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/coolo/citest.git
    stages:
    - pkglistgen:
        approval: manual
        jobs:
          openSUSE_Factory:
            resources:
            - repo-checker
            tasks:
            - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve --staging openSUSE:Factory:Staging:H --force

  Pkglistgen.Factory_Staging.I:
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    timer:
      spec: 0 */30 * ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/coolo/citest.git
    stages:
    - pkglistgen:
        approval: manual
        jobs:
          openSUSE_Factory:
            resources:
            - repo-checker
            tasks:
            - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve --staging openSUSE:Factory:Staging:I --force

  Pkglistgen.Factory_Staging.J:
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    timer:
      spec: 0 */30 * ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/coolo/citest.git
    stages:
    - pkglistgen:
        approval: manual
        jobs:
          openSUSE_Factory:
            resources:
            - repo-checker
            tasks:
            - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve --staging openSUSE:Factory:Staging:J --force

  Pkglistgen.Factory_Staging.K:
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    timer:
      spec: 0 */30 * ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/coolo/citest.git
    stages:
    - pkglistgen:
        approval: manual
        jobs:
          openSUSE_Factory:
            resources:
            - repo-checker
            tasks:
            - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve --staging openSUSE:Factory:Staging:K --force

  Pkglistgen.Factory_Staging.L:
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    timer:
      spec: 0 */30 * ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/coolo/citest.git
    stages:
    - pkglistgen:
        approval: manual
        jobs:
          openSUSE_Factory:
            resources:
            - repo-checker
            tasks:
            - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve --staging openSUSE:Factory:Staging:L --force

  Pkglistgen.Factory_Staging.M:
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    timer:
      spec: 0 */30 * ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/coolo/citest.git
    stages:
    - pkglistgen:
        approval: manual
        jobs:
          openSUSE_Factory:
            resources:
            - repo-checker
            tasks:
            - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve --staging openSUSE:Factory:Staging:M --force

  Pkglistgen.Factory_Staging.N:
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    timer:
      spec: 0 */30 * ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/coolo/citest.git
    stages:
    - pkglistgen:
        approval: manual
        jobs:
          openSUSE_Factory:
            resources:
            - repo-checker
            tasks:
            - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve --staging openSUSE:Factory:Staging:N --force

  Pkglistgen.Factory_Staging.O:
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    timer:
      spec: 0 */30 * ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/coolo/citest.git
    stages:
    - pkglistgen:
        approval: manual
        jobs:
          openSUSE_Factory:
            resources:
            - repo-checker
            tasks:
            - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve --staging openSUSE:Factory:Staging:O --force
  SLE15.SP1.Stagings.RelPkgs:
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 */10 * ? * *
      only_on_changes: false
    materials:
      scripts:
        git: https://github.com/coolo/citest.git
    stages:
    - Generate.Release.Package:
        approval: manual
        jobs:
          "Leap.Staging.A":
            resources:
              - repo-checker
            tasks:
              - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve
                 --staging openSUSE:Leap:15.1:Staging:A
                 --only-release-packages --force
          "Leap.Staging.B":
            resources:
              - repo-checker
            tasks:
              - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve
                 --staging openSUSE:Leap:15.1:Staging:B
                 --only-release-packages --force
          "Leap.Staging.C":
            resources:
              - repo-checker
            tasks:
              - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve
                 --staging openSUSE:Leap:15.1:Staging:C
                 --only-release-packages --force
          "Leap.Staging.D":
            resources:
              - repo-checker
            tasks:
              - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve
                 --staging openSUSE:Leap:15.1:Staging:D
                 --only-release-packages --force
          "Leap.Staging.E":
            resources:
              - repo-checker
            tasks:
              - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve
                 --staging openSUSE:Leap:15.1:Staging:E
                 --only-release-packages --force
  "Leap.Staging.A":
    environment_variables:
      STAGING_PROJECT: openSUSE:Leap:15.1:Staging:A
      STAGING_API: https://api.opensuse.org
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
      PYTHONPATH: /usr/share/openSUSE-release-tools
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    materials:
      stagings:
        git: http://botmaster.suse.de:4080/git/stagings.git
        auto_update: true
        whitelist:
          - openSUSE:Leap:15.1:Staging:A_-_standard.yaml
    stages:
    - "Check.Build.Succeeds":
        resources:
          - staging-bot
        tasks:
          - script: |-
              git clone https://github.com/coolo/citest.git
              cd citest
              python ./report-status.py -A $STAGING_API -p $STAGING_PROJECT -r standard -s pending
              python ./verify-repo-built-successful.py -A $STAGING_API -p $STAGING_PROJECT -r standard

    - "Update.000product":
        resources:
          - repo-checker
        tasks:
          - script: |-
              git clone https://github.com/coolo/citest.git
              cd citest

              if /usr/bin/osrt-pkglistgen --debug -A $STAGING_API update_and_solve --staging $STAGING_PROJECT --force; then
                python ./report-status.py -A $STAGING_API -p $STAGING_PROJECT -r standard -s success
              else
                python ./report-status.py -A $STAGING_API -p $STAGING_PROJECT -r standard -s failure
                exit 1
              fi
  "Leap.Staging.B":
    environment_variables:
      STAGING_PROJECT: openSUSE:Leap:15.1:Staging:B
      STAGING_API: https://api.opensuse.org
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
      PYTHONPATH: /usr/share/openSUSE-release-tools
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    materials:
      stagings:
        git: http://botmaster.suse.de:4080/git/stagings.git
        auto_update: true
        whitelist:
          - openSUSE:Leap:15.1:Staging:B_-_standard.yaml
    stages:
    - "Check.Build.Succeeds":
        resources:
          - staging-bot
        tasks:
          - script: |-
              git clone https://github.com/coolo/citest.git
              cd citest
              python ./report-status.py -A $STAGING_API -p $STAGING_PROJECT -r standard -s pending
              python ./verify-repo-built-successful.py -A $STAGING_API -p $STAGING_PROJECT -r standard

    - "Update.000product":
        resources:
          - repo-checker
        tasks:
          - script: |-
              git clone https://github.com/coolo/citest.git
              cd citest

              if /usr/bin/osrt-pkglistgen --debug -A $STAGING_API update_and_solve --staging $STAGING_PROJECT --force; then
                python ./report-status.py -A $STAGING_API -p $STAGING_PROJECT -r standard -s success
              else
                python ./report-status.py -A $STAGING_API -p $STAGING_PROJECT -r standard -s failure
                exit 1
              fi
  "Leap.Staging.C":
    environment_variables:
      STAGING_PROJECT: openSUSE:Leap:15.1:Staging:C
      STAGING_API: https://api.opensuse.org
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
      PYTHONPATH: /usr/share/openSUSE-release-tools
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    materials:
      stagings:
        git: http://botmaster.suse.de:4080/git/stagings.git
        auto_update: true
        whitelist:
          - openSUSE:Leap:15.1:Staging:C_-_standard.yaml
    stages:
    - "Check.Build.Succeeds":
        resources:
          - staging-bot
        tasks:
          - script: |-
              git clone https://github.com/coolo/citest.git
              cd citest
              python ./report-status.py -A $STAGING_API -p $STAGING_PROJECT -r standard -s pending
              python ./verify-repo-built-successful.py -A $STAGING_API -p $STAGING_PROJECT -r standard

    - "Update.000product":
        resources:
          - repo-checker
        tasks:
          - script: |-
              git clone https://github.com/coolo/citest.git
              cd citest

              if /usr/bin/osrt-pkglistgen --debug -A $STAGING_API update_and_solve --staging $STAGING_PROJECT --force; then
                python ./report-status.py -A $STAGING_API -p $STAGING_PROJECT -r standard -s success
              else
                python ./report-status.py -A $STAGING_API -p $STAGING_PROJECT -r standard -s failure
                exit 1
              fi
  "Leap.Staging.D":
    environment_variables:
      STAGING_PROJECT: openSUSE:Leap:15.1:Staging:D
      STAGING_API: https://api.opensuse.org
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
      PYTHONPATH: /usr/share/openSUSE-release-tools
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    materials:
      stagings:
        git: http://botmaster.suse.de:4080/git/stagings.git
        auto_update: true
        whitelist:
          - openSUSE:Leap:15.1:Staging:D_-_standard.yaml
    stages:
    - "Check.Build.Succeeds":
        resources:
          - staging-bot
        tasks:
          - script: |-
              git clone https://github.com/coolo/citest.git
              cd citest
              python ./report-status.py -A $STAGING_API -p $STAGING_PROJECT -r standard -s pending
              python ./verify-repo-built-successful.py -A $STAGING_API -p $STAGING_PROJECT -r standard

    - "Update.000product":
        resources:
          - repo-checker
        tasks:
          - script: |-
              git clone https://github.com/coolo/citest.git
              cd citest

              if /usr/bin/osrt-pkglistgen --debug -A $STAGING_API update_and_solve --staging $STAGING_PROJECT --force; then
                python ./report-status.py -A $STAGING_API -p $STAGING_PROJECT -r standard -s success
              else
                python ./report-status.py -A $STAGING_API -p $STAGING_PROJECT -r standard -s failure
                exit 1
              fi
  "Leap.Staging.E":
    environment_variables:
      STAGING_PROJECT: openSUSE:Leap:15.1:Staging:E
      STAGING_API: https://api.opensuse.org
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
      PYTHONPATH: /usr/share/openSUSE-release-tools
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    materials:
      stagings:
        git: http://botmaster.suse.de:4080/git/stagings.git
        auto_update: true
        whitelist:
          - openSUSE:Leap:15.1:Staging:E_-_standard.yaml
    stages:
    - "Check.Build.Succeeds":
        resources:
          - staging-bot
        tasks:
          - script: |-
              git clone https://github.com/coolo/citest.git
              cd citest
              python ./report-status.py -A $STAGING_API -p $STAGING_PROJECT -r standard -s pending
              python ./verify-repo-built-successful.py -A $STAGING_API -p $STAGING_PROJECT -r standard

    - "Update.000product":
        resources:
          - repo-checker
        tasks:
          - script: |-
              git clone https://github.com/coolo/citest.git
              cd citest

              if /usr/bin/osrt-pkglistgen --debug -A $STAGING_API update_and_solve --staging $STAGING_PROJECT --force; then
                python ./report-status.py -A $STAGING_API -p $STAGING_PROJECT -r standard -s success
              else
                python ./report-status.py -A $STAGING_API -p $STAGING_PROJECT -r standard -s failure
                exit 1
              fi
