format_version: 3
pipelines:
  Pkglistgen.openSUSE_Factory:
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 40 * ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/coolo/citest.git
    stages:
    - pkglistgen:
        approval:
          type: manual
        jobs:
          openSUSE_Factory:
            resources:
            - repo-checker
            tasks:
            - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve -p openSUSE:Factory
          openSUSE_Factory_ARM:
            resources:
            - repo-checker
            tasks:
            - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve -p openSUSE:Factory:ARM
          openSUSE_Factory_PowerPC:
            resources:
            - repo-checker
            tasks:
            - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve -p openSUSE:Factory:PowerPC
          openSUSE_Factory_zSystems:
            resources:
            - repo-checker
            tasks:
            - script: /usr/bin/osrt-pkglistgen -A https://api.opensuse.org update_and_solve -p openSUSE:Factory:zSystems
  Update.Repos.Factory:
    group: openSUSE.pkglistgen
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 0 21 ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/coolo/citest.git
    stages:
    - Update:
        approval:
          type: manual
        jobs:
          Factory:
            tasks:
             - script: /usr/bin/osrt-pkglistgen --apiurl https://api.opensuse.org handle_update_repos openSUSE:Factory
          Factory_ARM:
            tasks:
             - script: /usr/bin/osrt-pkglistgen --apiurl https://api.opensuse.org handle_update_repos openSUSE:Factory:ARM
          Factory_PowerPC:
            tasks:
             - script: /usr/bin/osrt-pkglistgen --apiurl https://api.opensuse.org handle_update_repos openSUSE:Factory:PowerPC

