---
format_version: 3
pipelines:
  SLE15.SP1.Stagings.RelPkgs:
    environment_variables:
      OSC_CONFIG: /home/go/.oscrc-staging-bot
    group: SLE15.SP1.Stagings
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 */10 * ? * *
      only_on_changes: false
    materials:
      scripts:
        git: https://github.com/coolo/citest.git
    stages:
      - Generate.Release.Package:
        approval:
          type: manual
        jobs:
          SLE.15.SP1.Staging.A:
            timeout: 0
            resources:
              - repo-checker
            tasks:
              - script: /usr/bin/osrt-pkglistgen -A ibs update_and_solve
                  --staging SUSE:SLE-15-SP1:GA:Staging:A
                  --only-release-packages --force
