format_version: 3
pipelines:
  ToTestManager.openSUSE_Factory:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/coolo/osc-plugin-factory.git
        branch: totest_manager_refact
        destination: scripts
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --osc-debug --dry --debug run openSUSE:Factory
  ToTestManager.openSUSE_Factory_ARM:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/coolo/osc-plugin-factory.git
        branch: totest_manager_refact
        destination: scripts
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --osc-debug --dry --debug run openSUSE:Factory:ARM
  ToTestManager.openSUSE_Factory_PowerPC:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/coolo/osc-plugin-factory.git
        branch: totest_manager_refact
        destination: scripts
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --osc-debug --dry --debug run openSUSE:Factory:PowerPC
  ToTestManager.openSUSE_Factory_zSystems:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/coolo/osc-plugin-factory.git
        branch: totest_manager_refact
        destination: scripts
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --osc-debug --dry --debug run openSUSE:Factory:zSystems
  ToTestManager.openSUSE_Leap_15.0_Images:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/coolo/osc-plugin-factory.git
        branch: totest_manager_refact
        destination: scripts
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --osc-debug --dry --debug run openSUSE:Leap:15.0:Images
  ToTestManager.openSUSE_Leap_15.1_Images:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/coolo/osc-plugin-factory.git
        branch: totest_manager_refact
        destination: scripts
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --osc-debug --dry --debug run openSUSE:Leap:15.1:Images
  ToTestManager.openSUSE_Leap_15.1_ARM_Images:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/coolo/osc-plugin-factory.git
        branch: totest_manager_refact
        destination: scripts
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --osc-debug --dry --debug run openSUSE:Leap:15.1:ARM:Images
  ToTestManager.openSUSE_Leap_15.1:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/coolo/osc-plugin-factory.git
        branch: totest_manager_refact
        destination: scripts
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --osc-debug --dry --debug run openSUSE:Leap:15.1
  ToTestManager.openSUSE_Leap_15.1_ARM:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/coolo/osc-plugin-factory.git
        branch: totest_manager_refact
        destination: scripts
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --osc-debug --dry --debug run openSUSE:Leap:15.1:ARM
  ToTestManager.openSUSE_Leap_15.1_PowerPC:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/coolo/osc-plugin-factory.git
        branch: totest_manager_refact
        destination: scripts
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --osc-debug --dry --debug run openSUSE:Leap:15.1:PowerPC
