format_version: 3
pipelines:
  Test.TTM:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/coolo/osc-plugin-factory.git
        branch: fix_ttm
        destination: scripts
    timer:
      spec: 0 */15 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            install -D /home/go/config/openqa-client.conf /home/go/.config/openqa/client.conf
            scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Leap:15.1
