format_version: 3
pipelines:
  ToTestManager:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/coolo/osc-plugin-factory.git
        branch: totest_manager_refact
        destination: scripts
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        jobs:
          openSUSE_Factory:
            resources:
            - staging-bot
            tasks:
            - script: |-
                ./totest-manager.py -A https://api.opensuse.org --osc-debug --dry --debug run openSUSE:Factory
          openSUSE_Factory_ARM:
            resources:
            - staging-bot
            tasks:
            - script: |-
                ./totest-manager.py -A https://api.opensuse.org --osc-debug --dry --debug run openSUSE:Factory:ARM
          openSUSE_Factory_PowerPC:
            resources:
            - staging-bot
            tasks:
            - script: |-
                ./totest-manager.py -A https://api.opensuse.org --osc-debug --dry --debug run openSUSE:Factory:PowerPC
          openSUSE_Factory_zSystems:
            resources:
            - staging-bot
            tasks:
            - script: |-
                ./totest-manager.py -A https://api.opensuse.org --osc-debug --dry --debug run openSUSE:Factory:zSystems
          openSUSE_Leap_15_0_Images:
            resources:
            - staging-bot
            tasks:
            - script: |-
                ./totest-manager.py -A https://api.opensuse.org --osc-debug --dry --debug run openSUSE:Leap:15.0:Images
          openSUSE_Leap_15_1_Images:
            resources:
            - staging-bot
            tasks:
            - script: |-
                ./totest-manager.py -A https://api.opensuse.org --osc-debug --dry --debug run openSUSE:Leap:15.1:Images
          openSUSE_Leap_15_1_ARM_Images:
            resources:
            - staging-bot
            tasks:
            - script: |-
                ./totest-manager.py -A https://api.opensuse.org --osc-debug --dry --debug run openSUSE:Leap:15.1:ARM:Images
          openSUSE_Leap_15_1:
            resources:
            - staging-bot
            tasks:
            - script: |-
                ./totest-manager.py -A https://api.opensuse.org --osc-debug --dry --debug run openSUSE:Leap:15.1
          openSUSE_Leap_15_1_ARM:
            resources:
            - staging-bot
            tasks:
            - script: |-
                ./totest-manager.py -A https://api.opensuse.org --osc-debug --dry --debug run openSUSE:Leap:15.1:ARM
          openSUSE_Leap_15_1_PowerPC:
            resources:
            - staging-bot
            tasks:
            - script: |-
                ./totest-manager.py -A https://api.opensuse.org --osc-debug --dry --debug run openSUSE:Leap:15.1:PowerPC
